contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cnvprep channel"
    url: https://nfcore.slack.com/channels/cnvprep
    about: Discussion about the nf-core/cnvprep pipeline
